config/routes.rb
Postit::Application.routes.draw do
  resources :posts do
  	member do
  		post 'vote'
  	end
  	resources :comments do
  		member do
  			post 'vote'
  		end
  	end
  end

  resources :users
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root to: 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	has_many :votes, as: :voteable

	validates :body, presence: true

    def total_votes
  	  self.votes.where(vote: true).size - self.votes.where(vote: false).size
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_categories
  has_many :categories, through: :post_categories

  has_many :comments
  belongs_to :user

  has_many :votes, as: :voteable 

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true

  def total_votes
  	self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :posts
	has_many :comments
	has_many :votes

	has_secure_password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	unless logged_in?
  		flash[:error] = "You must be logged in to do that"
  		redirect_to root_path
  	end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	#Need before filter

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(params[:category])
		if @category.save
			flash[:notice] = "Added a New Category!"
			redirect_to posts_path
		else
			render 'new'
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_user

	def index
		@comments = Comment.where("post_id = ?", params[:post_id])
	end

	def new
		@comment = Comment.new(post_id: params[:post_id])
	end

	def create
		@comment = Comment.new(post_id: params[:post_id], body: params[:body], user_id: current_user.id)
		if @comment.save
			flash[:notice] = "Added a New Comment!"
			redirect_to posts_path
		else
			flash[:error] = "Invalid Comment"
			redirect_to post_path(Post.find(params[:post_id]))
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update_attributes(body: params[:body])
			flash[:notice] = "You Changed Your Comment!"
			redirect_to post_path(Post.find(params[:post_id]))
		else
			render 'edit'
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.delete
		redirect_to post_path(Post.find(params[:post_id]))
	end

	def vote
	    @comment = Comment.find(params[:comment_id])
	    Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
	    
	    respond_to do |format|
	    	format.html do
	    		redirect_to posts_path
	    	end
	    	format.js do

	    	end
	    end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, only: [:show, :new, :create, :edit, :update, :vote]

  def index
    @posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
    @categories = Category.all
  end

  def create
  	@post = Post.new(params[:post])
  	@post.user_id = current_user.id
  	if @post.save
  		flash[:notice] = "Post was created!"
  		redirect_to post_path(@post)
  	else
  		render :new
  	end
  end

  def edit
  	@post = Post.find(params[:id])
    @categories = @post.categories
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update_attributes(params[:post])
  		flash[:notice] = "Post Updated!"
  		redirect_to post_path(@post)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to posts_path
  end

  def vote
    @post = Post.find(params[:id])
    Vote.create(voteable: @post, user: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        redirect_to posts_path
      end
      format.js do

      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

#GET /login
def new
end

#POST /login
def create
	user = User.where(email: params[:email]).first
	if user
		if user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Logged In!"
			redirect_to root_path
		else
			flash[:error] = "Incorrect Password"
			redirect_to login_path
		end
	else
		flash[:error] = "Name doesn't exist"
		redirect_to login_path
	end
end

def destroy 
	session[:user_id] = nil
	session[:notice] = "Logged Out"
	redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	@user = User.new
end

def create
	@user = User.new(params[:user])
	if @user.save
		flash[:notice] = "Thank for Joining :)"
		session[:user_id] = @user.id
		redirect_to root_path
	else
		render 'new'
	end
end

def show
	@user = User.find(params[:id])
end

def edit
	@user = User.find(params[:id])
end

def update 
	@user = User.find(params[:id])
	if @user.update_attributes(params[:post])
		flash[:notice] = "Updated Information"
		redirect_to root_path
	else
		render 'edit'
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png"
	end

	def avatar_url_small(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}?s=28.png"
	end
end

app/views/categories/new.html.erb
<h4 class="page-header">New Category</h4>
<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br/>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/categories/show.html.erb
<div class="page-header my-header">
	<h3><%= @category.name %> Posts</h3>
	<ul>
	<% Category.all.each do |category| %>
		<li><%= link_to "#{category.name}", category_path(category), class: "btn btn-small btn-success" %></li>
	<% end %>
	</ul>
</div>

<% @category.posts.each do |post| %>
	
	<div class="well text-center vote-box">
		<%= link_to "Upvote", vote_post_path(post, vote: true), method: 'post', remote: true %>
		<span id="post_<%= post.id %>_total"><%= post.total_votes.to_s %></span>
		<%= link_to "Downvote", vote_post_path(post, vote: false), method: 'post', remote: true %>
	</div>

	<div class="well post-header">
		<ul>
			<% post.categories.each do |category| %>
				<li><a class="btn btn-mini btn-success"><%= category.name %></a></li>
			<% end %>
		</ul>
		<h4>
			<%= post.title %> 
			<small class="quiet"> by </small>
			<span class="text-info"><%= post.user.name %><%= image_tag avatar_url_small(post.user) %></span>
			<small class="quiet"><%= time_ago_in_words(post.created_at) %> ago </small>
		</h4>
		<p class="quiet"><%= post.description %></p>
		<%= link_to "#{post.url}", "http://#{post.url}", class: "no-hover" %>
		<small><%= link_to "#{post.comments.count} comments", post_path(post), class: "no-hover" %></small>
	</div>
<% end %>

app/views/comments/edit.html.erb
<div class="well"><%= @comment.body %></div>
<%= form_tag "/posts/#{params[:post_id]}/comments/#{params[:id]}", method: "put", class:"form-horizontal" do %>
	<%= label_tag(:body, "Edit Comment") %>
	<%= text_area_tag(:body) %>
	<%= submit_tag("Edit Post", class:"btn btn-primary") %>
<% end %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
	<p><%= comment.body %></p>
<% end %>

app/views/comments/vote.js.erb
$('#comment_<%= @comment.id %>_total').html('<%= @comment.total_votes.to_s %>');

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "PostIt", root_path, class:"brand" %>
  </li>
 <% if logged_in? %>
  <li>
    <%= link_to 'All Posts', posts_path %>
  </li>
  <li>
  	<a class="new-post-button" href="<%= new_post_path %>"><i class="icon-plus icon-white"></i>New Post</a>
  </li>
  <li>
    <a class="new-category-button" href="<%= new_category_path %>"><i class="icon-plus icon-white"></i>New Category</a>
  </li>
</ul>
<ul class="nav pull-right">
  <li>
  	<%= link_to "#{current_user.name}", user_path(current_user) %>
  </li>
  <li>
  	<%= link_to 'Logout', logout_path %>
  </li>
</ul>
 <% else %>
  <li>
  	<%= link_to 'Login', login_path %>
  </li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
            <%= render 'layouts/navigation' %>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<%= f.label :description %>
	<%= f.text_area :description, :rows => "4" %>
	<%= f.label :category %>
	<% #Put in select %>
	<%= f.select :category_ids, @categories.collect{|c| [c.name, c.id]}, {}, {multiple: 'multiple'}%>
	<br/>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h3 class="page-header">Edit Post</h3>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header my-header">
	<h3>Posts</h3>
	<ul>
	<% Category.all.each do |category| %>
		<li><%= link_to "#{category.name}", category_path(category), class: "btn btn-small btn-success" %></li>
	<% end %>
	</ul>
</div>

<% @posts.sort_by! {|obj| obj.total_votes }.reverse.each do |post| %>
	
	<div class="well text-center vote-box">
		<%= link_to "Upvote", vote_post_path(post, vote: true), method: 'post', remote: true %>
		<span id="post_<%= post.id %>_total"><%= post.total_votes.to_s %></span>
		<%= link_to "Downvote", vote_post_path(post, vote: false), method: 'post', remote: true %>
	</div>

	<div class="well post-header">
		<ul>
			<% post.categories.each do |category| %>
				<li><a class="btn btn-mini btn-success"><%= category.name %></a></li>
			<% end %>
		</ul>
		<h4>
			<%= post.title %> 
			<small class="quiet"> by </small>
			<span class="text-info"><%= post.user.name %><%= image_tag avatar_url_small(post.user) %></span>
			<small class="quiet"><%= time_ago_in_words(post.created_at) %> ago </small>
		</h4>
		<p class="quiet"><%= post.description %></p>
		<%= link_to "#{post.url}", "http://#{post.url}", class: "url-display" %>
		<%= link_to "#{post.comments.count} comments", post_path(post), class: "comments-display" %>
	<% if current_user == post.user %>
		<p class="post-edit-delete">
			<small><%= link_to 'Edit', edit_post_path(post) %></small>
			<small> | </small>
			<small><%= link_to 'Delete', "/posts/#{post.id}", method: 'delete' %></small>
		</p>
	<% end %>
	</div>

<% end %>

app/views/posts/new.html.erb
<h3 class="page-header">Create a new post</h3>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="well text-center vote-box">
		<%= link_to "Upvote", vote_post_path(@post, vote: true), method: 'post' %>
		<%= @post.total_votes.to_s %>
		<%= link_to "Downvote", vote_post_path(@post, vote: false), method: 'post' %>
	</div>

<div class="well post-header">
		<ul>
			<% @post.categories.each do |category| %>
				<li><a class="btn btn-mini btn-success"><%= category.name %></a></li>
			<% end %>
		</ul>
		<h4>
			<span class="title"><%= @post.title %></span>
			<small class="quiet"> by </small>
			<span class="text-info"><%= @post.user.name %><%= image_tag avatar_url_small(@post.user) %></span>
			<small class="quiet"><%= time_ago_in_words(@post.created_at) %> ago</small>
		</h4>
		<p class="quiet"><%= @post.description %></p>
		<%= link_to "#{@post.url}", "http://#{@post.url}" %>
</div>
<% @post.comments.each do |comment| %>
	<div class="well comments-list">
			<p>
				<small>
					<%= comment.body %>
					<span class="quiet"> by </span>
					<span class="text-info"><%= comment.user.name %></span>
					<small class="quiet"><%= time_ago_in_words(@post.created_at) %> ago </small>
				</small>
				<% if comment.user == current_user %>
					<%= link_to "Edit", edit_post_comment_path(@post, comment), class: "btn btn-mini btn-warning hiding" %>
					<%= link_to "Delete", "#{params[:id]}/comments/#{comment.id}", method: "delete", class: "btn btn-mini btn-danger hiding" %>
				<% end %>
			</p>
			<div class="comments-vote-box">
				<small>
				<%= link_to "Upvote", vote_post_comment_path(comment, vote: true, comment_id: comment.id), method: 'post', remote: true %>
				<span id="comment_<%= comment.id %>_total"><%= comment.total_votes.to_s %></span>
				<%= link_to "Downvote", vote_post_comment_path(comment, vote: false, comment_id: comment.id), method: 'post', remote: true %>
			    </small>
	        </div>
	</div>
<% end %>
<% if logged_in? %>
	<%= form_tag "#{params[:id]}/comments", method: "post", class:"form-horizontal new-comment-form" do %>
		<%= label_tag(:body, "") %>
		<%= text_area_tag(:body) %>
		<%= submit_tag("New Comment", class:"btn btn-primary") %>
	<% end %>
<% end %>

app/views/posts/vote.js.erb
$('#post_<%= @post.id %>_total').html('<%= @post.total_votes.to_s %>');

app/views/users/edit.html.erb
<h4 class="page-header">Edit User Account</h4>

<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br/>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br/>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br/>
	<%= f.submit "Edit Account!", class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<h4 class="page-header">Register</h4>

<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br/>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br/>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br/>
	<%= f.submit "Create Account!", class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<h3><%= current_user.name %>'s Profile</h3>
<%= image_tag avatar_url(current_user) %>
<br/>
<%= link_to 'Edit Information', edit_user_path(@user), class: "btn btn-primary edit-profile-button" %>